#   This file is part of the kambpf project (https://github.com/zdule/part_ii_project).
#   It is file is only offered under the GPLv2 license.
#   For more information see the LICENSE file at the root of the project.
#
#   Copyright 2020 Dusan Zivanovic

obj-m += kambpf.o
kambpf-y := kambpf_main.o asm_handler.o kambpf_probe.o
ccflags-y := -I$(KAMPROBES_INCLUDE_DIR) -I/usr/local/include
