#   This file is part of the kambpf project (https://github.com/zdule/part_ii_project).
#   It is file is only offered under the GPLv2 license.
#   For more information see the LICENSE file at the root of the project.
#
#   Copyright 2020 Dusan Zivanovic

obj-m += test_module_main.o
test_module_main-objs += test_module.o tests/probes_correctness/kernel.o tests/probes_safety/kernel.o  tests/probes_safety/asm.o dummy_functions/dummy.o

ccflags-y := -I/usr/local/include
